spring:
  application:
    name: storageservice
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.cert

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system:14268/api/traces

cloud:
  aws:
    credentials:
      accessKey: demo:demo
      secretKey: DEMO_PASS
    endpoint: http://127.0.0.1:6007
    region: us-east-1
