---
# Source: storageservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageservice
  labels:
    helm.sh/chart: storageservice-0.1.0
    app: storageservice
    version: v1
    app.kubernetes.io/name: storageservice
    app.kubernetes.io/instance: storageservice
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
---
# Source: storageservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: storageservice
  labels:
    helm.sh/chart: storageservice-0.1.0
    app: storageservice
    version: v1
    app.kubernetes.io/name: storageservice
    app.kubernetes.io/instance: storageservice
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8080
      protocol: TCP
      name: nginx
  selector:
    app: storageservice
    version: v1
    app.kubernetes.io/name: storageservice
    app.kubernetes.io/instance: storageservice
---
# Source: storageservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageservice
  labels:
    helm.sh/chart: storageservice-0.1.0
    app: storageservice
    version: v1
    app.kubernetes.io/name: storageservice
    app.kubernetes.io/instance: storageservice
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storageservice
      version: v1
      app.kubernetes.io/name: storageservice
      app.kubernetes.io/instance: storageservice
  template:
    metadata:
      labels:
        app: storageservice
        version: v1
        app.kubernetes.io/name: storageservice
        app.kubernetes.io/instance: storageservice
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: storageservice
      securityContext:
        {}
      containers:
        - name: storageservice
          securityContext:
            {}
          image: "docker.pkg.github.com/300kks/storageservice/storageservice:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
          resources:
            {}

